### ISSUE TITLE
Requirement on the READ_PHONE_STATE permission

### ISSUE THREAD

**Issue by akien-mga** [mikifus/padland#12]
Hi there,

I just discovered your interesting app on [F-Droid](https://f-droid.org/wiki/page/com.mikifus.padland), being a pad junkie myself I'm looking forward to trying it.

When trying to install it though I was a bit puzzled to see that it asks for access to the phone state and identity (`android.permission.READ_PHONE_STATE`, https://github.com/mikifus/padland/blob/master/app/src/main/AndroidManifest.xml#L14). It also asks for access to the SD card contents and network connection, but those two sound pretty normal for the app's purpose.

I'm a bit touchy about what applications want to access from my personal data, and I'm not sure to understand why knowing the phone state and identity would be relevant. Could you clarify the situation?

Thanks in advance.

*Edit:* I checked the git history and apparently it has always been required: https://github.com/mikifus/padland/blob/565a289d06380baaa107e33b5b1c45c73a712d58/app/src/main/AndroidManifest.xml#L13

**Comment by mikifus** [comment]
This has been fixed in the lastest version.

**Comment by akien-mga** [comment]
Confirmed, I just installed it from F-droid :)
