### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Poussinou** [mikifus/padland#13]
Hello guys, (sorry for my bad english...)

I'm very new to github.
So i wrote the french translation for this app, and pull a request, but it's on my own repo. Because this is the first time I pull a request, I don't know if you're able to see or to use my new file?

It'll be great if someone can tell me if I have something else to do, or if I did something wrong... ^^"
Tell me if I have something else to do in my translation :)

Thanks for attention and bye

**Comment by mikifus** [comment]
Hi Poussinou,

The important thing is that you want to contribute and learn, so thank you in the first place.

You did the translation well but missed a detail: when you did the Pull Request you made it from "Poussinou-patch-1" to from "master". This is all happening in your repository. And it's okay!

I guess you tried to do this procedure:
1- Make a new branch (Poussinou-patch-1).
2- Do the translation in the branch
3- Merge your branch to your "master".
4- Pull Request from your master to my master.

So you need to finish the last two steps. Don't be afraid to ask if you don't understand something.

**Comment by Poussinou** [comment]
Thanks for your encouragements mikifus

I'll have a look tomorrow, maybe I might need some help indeed...

**Comment by Poussinou** [comment]
It's done (I think^^)
I just created a folder and put the translated file string.xml. Something else to do?

**Comment by mikifus** [comment]
I merged the pull request. I found some missing escaped apostrofes but corrected them, you might update your own repo and keep it to add new translations in the future.

Thanks!

**Comment by Poussinou** [comment]
Ok thanks a lot for the help :)
