### ISSUE TITLE
Bug tracking via email or via GitHub?

### ISSUE THREAD

**Issue by Airon90** [mikifus/padland#21]
In About section of the app you say:

> This app is under development. To provide feedback and report bugs please contact with the developer at xxx@yyy.zzz

Are you sure that reporting bugs should be done via email and not via GitHub?

**Comment by mikifus** [comment]
Hi,

Some people does not use github so I put my email. I shared it with some regular users to try it. The repo url is there as well, so advanced users are pleased too.

At this time I could already remove it because there isn't any known bug and people is being really helpful in Github.
