### ISSUE TITLE
support for pads with authentication

### ISSUE THREAD

**Issue by obifur** [mikifus/padland#24]
It doesn't prompt for authentication.. It says "Authentication required" when I try to access the pad. (I'm running a custom server)

**Comment by mikifus** [comment]
I guess you mean this happens with http auth, right?

**Comment by obifur** [comment]
yes

**Comment by mikifus** [comment]
Hi,

Please, try the apk version in the following link and confirm it fits your needs.
https://github.com/mikifus/padland/releases/tag/v1.2.2-alpha

It should be available in F-droid in a couple of days.

**Comment by obifur** [comment]
Hello, 
yes, it is working as expected. Thank you very much for your effort and this app!
:)

**Comment by obifur** [comment]
Hi, 
up to now it hasn't reached f-droid..

**Comment by mikifus** [comment]
@obifur Yes, my bad, I forgot a parameter. It should be available in one to two days.

**Comment by obifur** [comment]
Unfortunately 1.3-beta doesn't  work for me..

https://gist.github.com/anonymous/c93ac9dc8610ad9fecabad26fd095cb4

**Comment by mikifus** [comment]
Hi @obifur,

You mean on trying to do auth or the whole App? In the second case let's open a new issue.

**Comment by obifur** [comment]
The app starts normally and I could enter my custom server etc. But when I try to open the pad the app crashes. I don't get to enter the credentials.

**Comment by obifur** [comment]
1.3.1-beta works again, but the login looks like this (Text is missing, but it works):

![screenshot_20161030-172032](https://cloud.githubusercontent.com/assets/6723991/19839966/54a55a42-9eec-11e6-8dff-df30f92f869c.png)
