### ISSUE TITLE
No error when using HTTPS and unknown certificate

### ISSUE THREAD

**Issue by Chewie9999** [mikifus/padland#31]
Hardware: Fairphone 2
Android: 5.1 patch level 5th October 2016
Build: r4275.1_FP2_gms66_1.8.1

When trying to use an already created pad from a custom server on HTTPS, if the CA is unknown by Android, a blank white screen is displayed without any error.
Once you install the certificate manually, the pad does display.
Could some kind of error be displayed when the certificate is not known/trusted rather than a blank screen, as not all users would know that it could be an SSL problem.

**Comment by mikifus** [comment]
Hi,

Can you please confirm that this new version solves your issue?
https://github.com/mikifus/padland/releases/tag/v1.3.3

Thanks for your contribution.

**Comment by Chewie9999** [comment]
Hi Mikifus,
I have downloaded and installed it, and now it says "SSL certificate is untrusted", which is an improvement :)
It would be nice if there is a way of allowing it/making it an exception (like you can with Firefox), or is that a limitation somewhere?

Thanks!

**Comment by mikifus** [comment]
Hi,

The app uses a WebView object to show the pad. This means that in order to use your own certificate you should make it available globally on Android. I guess there should be an app or an option in order to manage certificates. It would make more sense than having to make a certificate manager for each app.

http://stackoverflow.com/a/22040887

Please share your thoughs on this issue and tell me if you find aworkaround.

**Comment by Chewie9999** [comment]
That's fine - I did add my certificate, so it's all ok for me, but I was just thinking for more non-technical users I would think an option for them would be handy - or maybe a link on how to do it if you can't do it within the application itself.
Thanks!

**Comment by mikifus** [comment]
I think that managing certificates would be overkill for the app. It's far beyond its functions and those certificates won't work for other apps.

I can only think of one solution: adding a link to the message. That link should make clear how to add your own certificates. Do you know any good resource? It should be a link that works on the long term too, so I won't go with a SO question.

**Comment by Chewie9999** [comment]
Fair enough.
There's this:
https://support.google.com/nexus/answer/2844832
Although it mentions the "Personal" step, which I dont have on my Android 5.1 version, but the rest is the same, and at least it's official!
Would that do?

**Comment by mikifus** [comment]
Yes. That link will do. It gets even automatically translated. I did the implementation by just adding a "Learn more" button on the error dialog.

Thanks for your feedback!
