### ISSUE TITLE
ListView changes state on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [mikifus/padland#32]
When I perform this sequence of events, the scrollable view on screen goes back to the top:

1. Click on Settings Icon
2. Scroll Down
3. Orientation Change

**Comment by mikifus** [comment]
I can't reproduce this behavior. I need more details. Please make sure you have the latest version.

**Comment by reverse-unina** [comment]
I was running version 1.3.2. This issue is fixed in version 1.3.3 
Thank you
