### ISSUE TITLE
Doubled slash in custom pad urls, if server url has a trailing slash

### ISSUE THREAD

**Issue by HairyFotr** [mikifus/padland#35]
Reproduction: If a trailing slash / is written by the user in the custom server url field (for example `http://mypadserver.com/` (is not a real etherpad site)), padland will generate pad urls such as `http://mypadserver.com//p/some-pad`, with two slashes, which fails to load properly.

Fix suggestion: padland should not add an extra / if the url already ends with it.

(And btw thanks for a great app!)

**Comment by HairyFotr** [comment]
Additionally, the existing pad urls are not updated when I change the server url - I need to re-add the pads manually.

**Comment by mikifus** [comment]
Hi, thank you for your feedback.

I've solved the trailing slash bug (a new branch) but I have some concerns regarding the update function.

The already created pads are saved by name and url, but not the server_id. Also the default servers have no ID, it will conflict with the custom ones. This is the simplest approach.
Updating all the urls may be done by looking for url matches with the old one, which can lead to glitches, so I am not sure about that method. Do you have any proposal?

**Comment by HairyFotr** [comment]
Thanks!
I had a feeling it might be implemented this way. I think it's not a big problem if it stays like it is - for incorrect server urls you notice when adding the first pad, and server domain moves (which would require readding multiple pads) are probably rare.

**Comment by mikifus** [comment]
Ok, I had that same view, when I tried to think on a good solution It required too deep structural changes.

Please, try out this beta release and tell me if it does work as you expected:
https://github.com/mikifus/padland/releases/tag/v1.3.5-beta
