### ISSUE TITLE
Creating and Opening oft Pad fails because oft wrong url

### ISSUE THREAD

**Issue by L1am0** [mikifus/padland#39]
Sadly the base function of the app does not work.
How I get the issue:
1) Click on Create new Pad
2) Type in Name (e.g. Testpad)
3) Click on Create or go to
4) Error pages show "Cannot GET /http://pad.riseup.net/p/test

When I look into the pad settings the app tells me that the pad URL is " http://pad.riseup.net/p/http://pad.riseup.net/p/test"

*Please remove the double occurencie of the URL.* Hopefully works again afterwards.

**Comment by mikifus** [comment]
Confirmed, I can't believe I didn't see this.
