### ISSUE TITLE
Black design

### ISSUE THREAD

**Issue by rugk** [mikifus/padland#4]
A black design (suitable for AMOLED screens) would be nice.

**Comment by NAVANEETHKNAIR** [comment]
AMOLED screens stand for better battery life, slimmer and sleek design, greater contrast, darker blacks, and better response time.
But the cost is comparatively higher than lcd.... 

Black design makes other colours visible

**Comment by NAVANEETHKNAIR** [comment]
<style name="AppTheme" parent="android:Theme.Holo.Light" />
 I change it to:

<style name="AppTheme" parent="android:Theme.Holo.Dark" />

**Comment by NAVANEETHKNAIR** [comment]
several themes are available in
https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/res/res/values/themes.xml

https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/res/res/values/styles.xml

**Comment by rugk** [comment]
@NAVANEETHKNAIR Maybe make a PR? (With an option in the settings of course)
