### ISSUE TITLE
Parse padname & server from URL

### ISSUE THREAD

**Issue by madduck** [mikifus/padland#44]
I often have a URL and right now, I have to manually cut out the pad name, as well as the server, when in fact this should be trivially possible for the app to do. Please consider this a wishlist! ;)

**Comment by mikifus** [comment]
Hi,

This should be quite straigthforward. The reason I didn't implement it like this is because the app is designed to only allow pads on the configured servers. This is done in order to prevent phishing attacks among other possible security problems.

Still I'll try to implement this.
