### ISSUE TITLE
Hide the chat window

### ISSUE THREAD

**Issue by madduck** [mikifus/padland#45]
When I load a pad, the chat window is always displayed in full size. I think it would be better if it started out minimalised, or smaller at least. Even better would be if the chat window could be displayed on a different panem such that I could swipe left and right to switch between pad and chat window. Thanks!

**Comment by mikifus** [comment]
Hi,

There's no current way to control the Etherpad interface from the app. I tried injecting javascript but it wasn't elegant and it didn't work at all.

The most reasonable solution would be developing a plugin for Etherpad Lite that provided an API for interface control. That way an Etherpad site would have the option to be controlled by a wrapper UI. 

This could imply serious security issues and must be done carefully.

**Comment by mikifus** [comment]
So Etherpad is now much more mobile-friendly so I'm going to close this issue.
