### ISSUE TITLE
"onReceivedError" does not execute in API level < 23.

### ISSUE THREAD

**Issue by strooonger** [mikifus/padland#47]
Hi,

I found that you have used `onReceivedError(WebView view, WebResourceRequest request, WebResourceError error)` in [PadViewActivity](https://github.com/mikifus/padland/blob/38f7e6651940f8cf603b860d53d9cd99d1935bd8/app/src/main/java/com/mikifus/padland/PadViewActivity.java), which is added in API level 23. However, it does not exist in API level < 22, meaning that the code logic you wrote to handle webview error will not take effect. (See this [link](https://stackoverflow.com/questions/32769505/webviewclient-onreceivederror-deprecated-new-version-does-not-detect-all-errors))

To fix this issue, add deprecated `onReceivedError (WebView view, int errorCode, String description, String failingUrl)` to make it compatible for API level < 22.

Thanks.

**Comment by mikifus** [comment]
Thanks, will be fixed in the next version.
