### ISSUE TITLE
Allow import/export/backup of pads

### ISSUE THREAD

**Issue by Porkepix** [mikifus/padland#50]
It would be a pretty handy feature to be able to import/export one or more pads, and also everything, for backup/transfer purpose.

**Comment by NA0341** [comment]
To clarify this:
A feature to **Backup Pads & Settings** would save a list of the pads, not their content. If you want to save pads you use the pad's own export feature.

**A backup feature would not be nice. It is absolutely needed!**

**Comment by NA0341** [comment]
@mikifus any news on this?

You could literally make this as simple as copying groups, entries & settings as json and import them from json as well. That's the way KISS - Launcher does it, for example.

**Comment by mikifus** [comment]
@NA0341 No news I'm afraid, but as I see there's demand I guess I should develop this feature next.

I assume it's simple to export some DB tables to JSON and then restore them, yet I'd add some complexity:
- Setting an export version in case the DB structure changes so import can take that into account (example: adding tags).
- Adding the whitelisted servers to the export.
- An export wizard could ask which info to export with checkboxes.
- The user could pick some pads from the list and hit export to only extract the selected data.
- Allow to export config settings as to restore the app status in full

Other issues I foresee:
- Having statistics in the same export block as the pads or have them apart and optional.
- Dealing with duplicates.
- Proper import errors being informed to the user.
- Related to previous: allow partial import informing about errors or block the whole import until no errors happen.
