### ISSUE TITLE
Allow to open an existing pad by giving the full URL

### ISSUE THREAD

**Issue by Porkepix** [mikifus/padland#52]
As stated in the summary, it should also be possible to open a pad by just giving the full URL.

**Comment by Porkepix** [comment]
Not sure about that as it's not that nice on the privacy-side, but Padland could "inspect" clipboard and see if it recognize a pad scheme/URL.

**Comment by mikifus** [comment]
This feature was included in this release for testing:
https://github.com/mikifus/padland/releases/tag/v1.4-beta

It'll only work with allowed servers in order to recognize valid urls.

**Comment by mikifus** [comment]
Closing due to fix.
