### ISSUE TITLE
Let's  Encrypt not supported?

### ISSUE THREAD

**Issue by Sudrien** [mikifus/padland#62]
Personal etherpad instance. Original connection worked, failed to accept ssl cert after a refresh.  Are ssl certs cached?

**Comment by mpepesitep** [comment]
This shouldn't be an issue. You gave no details to allow me to reproduce the error. Please check that there is no mistake in you Etherpad setup.

**Comment by Sudrien** [comment]
Apologies, as I have installed no authentication methods, I'm loathe to post a working url in a public forum. 

The installation is at https://[redacted]/etherpad/ - so served in a subdirectory, not root. I am able to access pads through the web interface.

In padland, I create a new document,  type in a name not currently being used, and get the prompt

> SSL Error
> SSL certificate ID mismatch
> [Learn More] [OK]

Learn more links to https://support.google.com/pixelphone/answer/2844832

...and now that I collect this I realize my current location's DNS server messes with some records, and this is not padland's fault.

I apologize for the misreport.
