### ISSUE TITLE
UI context corrections

### ISSUE THREAD

**Issue by NA0341** [mikifus/padland#64]
+ Default pad server | change »…a new one.« to »…a new pad.«
+ add missing ».« at line endings

**Comment by mikifus** [comment]
Could you please point out which line endings are missing a dot?

Here's the strings.xml file for English:
https://github.com/mikifus/padland/blob/master/app/src/main/res/values/strings.xml

**Comment by NA0341** [comment]
Hi sorry for the late reply :D

In Settings:

+ The description of `Auto-save new documents`, `Server list` & `Introduction` miss a dot at the end.
+ The description of `Server name` in dialog `New server` misses a dot at the end.

In Main View:

+ The description of the input field `Pad name (URL)` in dialog `Create pad` misses a dot.


That's all I found right now :)
