### ISSUE TITLE
Do not put binaries into repos

### ISSUE THREAD

**Issue by rugk** [mikifus/padland#8]
You should not place binaries into your repo. (here the apk file).

Rather publish them [in the releases section](https://github.com/mikifus/padland/releases).

**Comment by mikifus** [comment]
Hi, I saw many repos didn't provide the binaries so I understood it wasn't a good practise. I did it to provide my initial beta testers a place to download the apk. F-droid ignores the apk so it's not an issue for the repo.

I will remove it in a further update.
